apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: rtaylor
  name: resource-autoscaler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: resource-autoscaler
  labels:
    app: resource-autoscaler-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-autoscaler-controller
  template:
    metadata:
      labels:
        app: resource-autoscaler-controller
    spec:
      serviceAccountName: autoscaler
      containers:
        - name: controller
          image: starlord.inscloudgate.net/rtaylor/resource-autoscaler:alpha
          env:
            - name: VERBOSE
              value: "4"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-autoscaler-role
  namespace: resource-autoscaler
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler
  namespace: resource-autoscaler
imagePullSecrets:
  - name: starlord-image-pull-secret

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
  # name: autoscaler
  # namespace: resource-autoscaler
# roleRef:
  # apiGroup: rbac.authorization.k8s.io
  # kind: Role
  # name: resource-autoscaler-role
# subjects:
  # - kind: ServiceAccount
    # name: autoscaler
    # namespace: resource-autoscaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler
  namespace: resource-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-autoscaler-role
subjects:
  - kind: ServiceAccount
    name: autoscaler
    namespace: resource-autoscaler

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-traffic
  namespace: resource-autoscaler
spec:
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
  podSelector: {}
