apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: rtaylor
  name: resource-autoscaler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: resource-autoscaler
  labels:
    app: resource-autoscaler-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-autoscaler-controller
  template:
    metadata:
      labels:
        app: resource-autoscaler-controller
    spec:
      serviceAccountName: autoscaler
      containers:
        - name: controller
          image: starlord.inscloudgate.net/rtaylor/resource-autoscaler:alpha
          env:
            - name: VERBOSE
              value: "4"
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: resource-scaler-config

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-autoscaler-role
  namespace: resource-autoscaler
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments/scale
      - replicasets/scale
      - statefulsets/scale
    verbs:
      - get
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler
  namespace: resource-autoscaler
imagePullSecrets:
  - name: starlord-image-pull-secret

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
  # name: autoscaler
  # namespace: resource-autoscaler
# roleRef:
  # apiGroup: rbac.authorization.k8s.io
  # kind: Role
  # name: resource-autoscaler-role
# subjects:
  # - kind: ServiceAccount
    # name: autoscaler
    # namespace: resource-autoscaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler
  namespace: resource-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-autoscaler-role
subjects:
  - kind: ServiceAccount
    name: autoscaler
    namespace: resource-autoscaler

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-traffic
  namespace: resource-autoscaler
spec:
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
  podSelector: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-scaler-config
  namespace: resource-autoscaler
data:
  config.json: |
    [
      {
        "CPUPerReplica": 16,
        "Name": "cpu scaler",
        "Target": {
          "Name": "nginx",
          "Namespace": "default",
          "Type": "deployment"
        }
      },
      {
        "MemoryPerReplica": 100e9,
        "Name": "scale on memory",
        "Target": {
          "Name": "nginx",
          "Namespace": "default",
          "Type": "deployment"
        }
      }
    ]
